spring:
  application.name: inventory-service
  cloud:
    function:
      definition: inventoryCheck
    stream:
      bindings:
        inventoryCheck-in-0.destination: ${order.processor.name}.inventoryCheck
        inventoryCheck-out-0.destination: ${order.processor.name}.orderStatus
      kafka:
        bindings:  #SERDES BINDING
          inventoryCheck-in-0:
            consumer.configuration.value.deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
          inventoryCheck-out-0:
            producer.configuration.value.serializer: org.springframework.kafka.support.serializer.JsonSerializer
        streams:
          bindings: # Assigning unique application id to every consumer
            inventoryCheck-in-0.consumer.configuration.application.id: ${order.processor.name}-inventoryCheck
          binder:
            brokers: localhost:9092 # just to use it in the service app, Its already 'localhost:9092' by default
            application.id: ${spring.application.name}
