spring:
  application.name: client-service
  cloud:
    function:
      definition: shippedConsumer
    stream:
      bindings:
        shippedConsumer-in-0.destination: ${order.processor.name}.shipping
      kafka:
        bindings:  #SERDES BINDING
          shippedConsumer-in-0:
            consumer.configuration.value.deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        streams:
          bindings: # Assigning unique application id to every consumer
            shippedConsumer-in-0.consumer.configuration.application.id: ${order.processor.name}-shipped
          binder:
            brokers: localhost:9092 # just to use it in the service app, Its already 'localhost:9092' by default
            application.id: ${spring.application.name}