spring:
  application.name: delivery-service
  cloud:
    function:
      definition: deliveryProcess
    stream:
      bindings:
        deliveryProcess-in-0.destination: ${order.processor.name}.shipping
        deliveryProcess-out-0.destination: ${order.processor.name}.orderStatus
      kafka:
        bindings:  #SERDES BINDING
          deliveryProcess-in-0:
            consumer.configuration.value.deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
          deliveryProcess-out-0:
            producer.configuration.value.serializer: org.springframework.kafka.support.serializer.JsonSerializer
        streams:
          bindings: # Assigning unique application id to every consumer
            deliveryProcess-in-0.consumer.configuration.application.id: ${order.processor.name}-deliveryProcess
          binder:
            brokers: kafka-service:9092 # just to use it in the service app, Its already 'localhost:9092' by default
            application.id: ${spring.application.name}