spring:
  application.name: processor-service
  cloud:
    function:
      definition: orderStateStoreProcessor;orderProcess
    stream:
      bindings:
        orderStateStoreProcessor-in-0.destination: ${order.processor.name}.orderStatus
        orderStateStoreProcessor-out-0.destination: ${order.processor.name}.orderProcess

        #       orderProcess function use branch to forward the data to inventoryCheck,shipping and shippedConsumer
        #       orderProcess out is not required buz we are using branch to split and forward data to related topics
        orderProcess-in-0.destination: ${order.processor.name}.orderProcess
      kafka:
        bindings:  #SERDES BINDING
          orderStateStoreProcessor-in-0:
            consumer.configuration.value.deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
          orderStateStoreProcessor-out-0:
            producer.configuration.value.serializer: org.springframework.kafka.support.serializer.JsonSerializer
          orderProcess-in-0:
            consumer.configuration.value.deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
          orderProcess-out-0:
            producer.configuration.value.serializer: org.springframework.kafka.support.serializer.JsonSerializer
        streams:
          bindings: # Assigning unique application id to every consumer
            orderStateStoreProcessor-in-0.consumer.configuration.application.id: ${order.processor.name}-orderStateStoreProcessor
            orderProcess-in-0.consumer.configuration.application.id: ${order.processor.name}-orderProcess
          binder:
            brokers: localhost:9092 # just to use it in the service app, Its already 'localhost:9092' by default
            application.id: ${order.processor.name}
            auto-add-partitions: true
            min-partition-count: 1
            state-store-retry:
              max-attempts: 10
              backoff-period: 500
            configuration: # STREAM SERDES BINDING
              application.server: localhost:${server.port} # for InteractiveQueryService to describe itself
              state.dir: state-${order.processor.name}-${server.port} # to give a unique dir name in case you run multiple of this app on the same machine
              default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              commit.interval.ms: 1000
              auto.offset.reset: latest